import { useECGStore } from "@/store/useECGStore";
import { GlassCard } from "@/components/med/GlassCard";
import { Heart } from "lucide-react";
import { formatTimestamp } from "@/utils/formatters";

export function DoctorSummary() {
  const report = useECGStore((s) => s.reportData);
  if (!report) return null;

  const { features } = report.analysisResult;

  return (
    <GlassCard>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Heart className="w-5 h-5 text-med-primary" />
          <h2 className="text-lg font-semibold">Clinical Summary</h2>
        </div>
        <span className="text-xs text-text-muted">{formatTimestamp(report.analysisResult.timestamp)}</span>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="space-y-2">
          <h3 className="text-xs font-semibold text-text-secondary uppercase tracking-wider">Metrics</h3>
          <table className="w-full text-sm">
            <tbody>
              {[
                ["Heart Rate", `${features.heartRate} bpm`],
                ["RR Mean", `${Math.round(features.rrMean)} ms`],
                ["PR Interval", features.prInterval != null ? `${Math.round(features.prInterval)} ms` : "N/A"],
                ["QRS Duration", features.qrsDuration != null ? `${Math.round(features.qrsDuration)} ms` : "N/A"],
                ["QT Interval", features.qtInterval != null ? `${Math.round(features.qtInterval)} ms` : "N/A"],
                ["QTc (Bazett)", features.qtcInterval != null ? `${Math.round(features.qtcInterval)} ms` : "N/A"],
              ].map(([k, v]) => (
                <tr key={k} className="border-b border-border/50">
                  <td className="py-1.5 text-text-secondary">{k}</td>
                  <td className="py-1.5 font-mono text-right">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div>
          <h3 className="text-xs font-semibold text-text-secondary uppercase tracking-wider mb-2">
            All Probable Diagnoses ({report.analysisResult.diagnoses.length})
          </h3>
          <ul className="space-y-1.5">
            {[...report.analysisResult.diagnoses]
              .sort((a, b) => b.confidence - a.confidence)
              .map((d, i) => {
                const pct = (d.confidence * 100).toFixed(1);
                const dotColor =
                  d.severity === "normal"
                    ? "bg-med-secondary"
                    : d.severity === "warning"
                    ? "bg-med-warning"
                    : "bg-med-danger";
                const txtColor =
                  d.severity === "normal"
                    ? "text-med-secondary"
                    : d.severity === "warning"
                    ? "text-med-warning"
                    : "text-med-danger";
                return (
                  <li key={d.id} className="text-sm flex items-center justify-between gap-2">
                    <span className="flex items-center gap-2 min-w-0">
                      <span className="text-[10px] font-mono text-text-muted">#{i + 1}</span>
                      <span className={`w-2 h-2 rounded-full shrink-0 ${dotColor}`} />
                      <span className="truncate">{d.condition}</span>
                    </span>
                    <span className={`font-mono font-bold ${txtColor} shrink-0`}>{pct}%</span>
                  </li>
                );
              })}
          </ul>
        </div>
      </div>

      <p className="text-sm text-text-secondary leading-relaxed">{report.clinicianSummary}</p>

      <div className="mt-4 p-3 rounded-lg bg-med-warning/5 border border-med-warning/20">
        <p className="text-xs text-med-warning">⚠️ This report is generated by AI and requires clinical validation.</p>
      </div>
    </GlassCard>
  );
}
